apps/storm/urls.py
# ---------------------------
__author__='stormsha'
__date__='2019/3/10 21:03'
# ---------------------------



from django.conf.urls import url
from .views import (IndexView, DetailView, MessageView, AboutView, DonateView, ExchangeView, ProjectView, QuestionView, MySearchView, LoveView, LinkView)

urlpatterns = [
    # 首页
    url(r'^$', IndexView.as_view(template_name='index.html'), name='index'),  # 主页，自然排序
    url(r'^link/$', LinkView, name='link'),     # 申请友情链接
    url(r'^category/message/$', MessageView, name='message'),
    url(r'^category/about/$', AboutView, name='about'),
    url(r'^category/donate/$', DonateView, name='donate'),
    url(r'^category/exchange/$', ExchangeView, name='exchange'),
    url(r'^category/project/$', ProjectView, name='project'),
    url(r'^category/question/$', QuestionView, name='question'),
    # 分类页面
    url(r'^category/(?P<bigslug>.*?)/(?P<slug>.*?)', IndexView.as_view(template_name='content.html'), name='category'),
    # 归档页面
    url(r'^date/(?P<year>\d+)/(?P<month>\d+)/$', IndexView.as_view(template_name='archive.html'), name='date'),
    # 标签页面
    url(r'^tag/(?P<tag>.*?)/$', IndexView.as_view(template_name='content.html'), name='tag'),
    # 文章详情页面
    url(r'^article/(?P<slug>.*?)/$', DetailView.as_view(), name='article'),
    # 全文搜索
    url(r'^search/$', MySearchView.as_view(), name='search'),
    # 喜欢
    url(r'^love/$', LoveView, name='love')
]

apps/user/urls.py
from django.conf.urls import url
from .views import login_view, logout_view, register_view, profile_view, change_profile_view

urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^logout', logout_view, name='logout'),
    url(r'^register/$', register_view, name='register'),
    url(r'^profile/$', profile_view, name='profile'),
    url(r'^profile/change/$', change_profile_view, name='change_profile'),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from storm.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from storm.feeds import AllArticleRssFeed

from rest_framework.routers import DefaultRouter
from api import views as api_views
if settings.API_FLAG:
    router = DefaultRouter()
    router.register(r'users', api_views.UserListSet)
    router.register(r'articles', api_views.ArticleListSet)
    router.register(r'tags', api_views.TagListSet)
    router.register(r'categorys', api_views.CategoryListSet)

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 用户
    url(r'^accounts/', include('user.urls', namespace='accounts')),
    # storm
    url('', include('storm.urls', namespace='blog')),  # blog
    # 评论
    url(r'^comment/', include('comment.urls', namespace='comment')),  # comment
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),  # 网站地图
    url(r'^feed/$', AllArticleRssFeed(), name='rss'),   # rss订阅
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

if settings.API_FLAG:
    urlpatterns.append(url(r'^api/v1/', include(router.urls, namespace='api')))    # restframework

templates/archive.html
{%extends 'base_right.html'%}
{% load comment_tags %}
{% block title %}静觅丨文章归档{% endblock title %}
{% block description %}
    <meta name="description" content="文章按照月份分类归档。"/>
    {% endblock description %}
{% block keywords %}
    <meta name="keywords" content="网络爬虫工具,爬虫python,http代理,scrapy爬虫,爬虫代理ip,python为什么叫爬虫,python爬虫怎么赚钱"/>
    {% endblock keywords %}
{%block body%}
	<div class="content-wrap">
	    <div class="content">
		    <header class="archive-header">
			    <h1><i class="fa fa-folder-open"></i>  &nbsp;分类：福利专区  <a title="订阅福利专区" target="_blank" href="{% url 'blog:category' resources '' %}"><i class="rss fa fa-rss"></i></a></h1>
					</header>
        {% for article in page_obj %}
				<article class="excerpt">
	<header><a class="label label-important" href="/category/{{ article.category.bigcategory.name }}/{{ article.category.name|lower }}">{{ article.category.name }}<i class="label-arrow"></i></a><h2><a target="_blank" href="/article/{{ article.slug }}" title="{{ article.title }}">{{ article.title }} </a></h2>
	</header>
	<div class="focus"><a target="_blank" href="/article/{{ article.slug }}"><img class="thumb" width="200" height="123" src="{{ article.img_link }}" alt="{{ article.title }}" /></a></div>
			<span class="note"> {{ article.summary }}</span>
<p class="auth-span">
		<span class="muted"><i class="fa fa-user"></i> <a href="/author/{{ article.author }}">{{ article.author }}</a></span>
		<span class="muted"><i class="fa fa-clock-o"></i> {{ article.create_date|date:'Y-m-d'}}</span>	<span class="muted"><i class="fa fa-eye"></i> {{ article.views }}浏览</span>	<span class="muted"><i class="fa fa-comments-o"></i> <a target="_blank" href="/article/{{ article.slug }}#comments">{% get_comment_count article.id  article.id%}评论</a></span><span class="muted">
<a href="javascript:;" data-action="ding" data-id="455" id="Addlike" class="action"><i class="fa fa-heart-o"></i><span class="count">{{ article.love }}</span>喜欢</a></span></p>
</article>
        {% empty %}
                <div class="no-post">当前分类下还没有发布的文章！</div>
        {% endfor %}
{% if is_paginated %}
            <div class="pagination">
                <ul>
                    {% if first %}
                        <li><a href="?page=1">1</a></li>
                    {% endif %}
                    {% if left %}
                        {% if left_has_more %}
                            <li><span>...</span></li>
                        {% endif %}
                        {% for i in left %}
                            <li class="prev-page"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                    {% endif %}
                    <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                    {% if right %}
                        {% for i in right %}
                            <li class="next-page"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                        {% if right_has_more %}
                            <li><span>...</span></li>
                        {% endif %}
                    {% endif %}
                    {% if last %}
                        <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
        </div>
    </div>
{%endblock body%}

templates/base_right.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags static %}


{% block right %}
        <aside class="sidebar">
            <div class="widget widget_text">
                <div class="textwidget">
                    <div class="social">

                        <a href="https://weibo.com/stormsha" rel="external nofollow" title="新浪微博" target="_blank"><i class="sinaweibo fa fa-weibo"></i></a><a
                            href="" rel="external nofollow" title="腾讯微博" target="_blank"><i
                            class="tencentweibo fa fa-tencent-weibo"></i></a><a class="weixin"><i class="weixins fa fa-weixin"></i>
                        <div class="weixin-popover">
                            <div class="popover bottom in">
                                <div class="arrow"></div>
                                <div class="popover-title"></div>
                                <div class="popover-content"><img src="{% static 'images/个人微信.jpg' %}"></div>
                            </div>
                        </div>
                    </a>
                        <a href="http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=mail@stormsha.com" rel="external nofollow" title="Email"
                           target="_blank"><i class="email fa fa-envelope-o"></i></a>
                        <a href="/feed/" rel="external nofollow" target="_blank" title="订阅本站"><i class="rss fa fa-rss"></i></a>
                    </div>
                </div>
            </div>

            <div class="widget widget_metaslider_widget">
                <!--热门专题-->
                <div class="title"><h2>热门专题</h2></div><!-- meta slider -->
                <div style="width: 100%;" class="metaslider metaslider-nivo metaslider-2698 ml-slider meta-slider">
                    <div id="metaslider_container_2698">
                        <div class='slider-wrapper theme-bar'>
                            <div class='ribbon'></div>
                            <div id='metaslider_2698' class='nivoSlider'>
                                {% get_carousel_right as carousels %}
                                {% for carousel in carousels  %}
                                    <a href="{{ carousel.url }}" target="_blank">
                                        <img src="{{ carousel.img_url }}" height="300" width="320" data-title="{{ carousel.content }}"
                                             title="{{ carousel.title }}" alt="{{ carousel.title }}" class="slider-2698 slide-1720"/>
                                    </a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <!--热门专题结束-->

                    <script type="text/javascript">
                        var metaslider_2698 = function ($) {
                            $('#metaslider_2698').nivoSlider({
                                boxCols: 7,
                                boxRows: 5,
                                pauseTime: 3000,
                                effect: "random",
                                controlNav: false,
                                directionNav: true,
                                pauseOnHover: true,
                                animSpeed: 600,
                                prevText: "&lt;",
                                nextText: "&gt;",
                                slices: 15,
                                manualAdvance: false
                            });
                        };
                        var timer_metaslider_2698 = function () {
                            var slider = !window.jQuery ? window.setTimeout(timer_metaslider_2698, 100) : !jQuery.isReady ? window.setTimeout(timer_metaslider_2698, 1) : metaslider_2698(window.jQuery);
                        };
                        timer_metaslider_2698();
                    </script>
                </div>
                <!--// meta slider-->
            </div>
            <!--广告位-->
            <div class="widget widget_text">
                <div class="textwidget">
                    <a href="/"><img style="width:100%" src="{% static 'images/weixin.png' %}"/></a>
                </div>
            </div>
            <!--广告位结束-->
            <div class="widget widget_archive">

                <!--文章归档-->
                <div class="title"><h2>文章归档</h2></div>
                    {% get_data_date as data_date %}
                    <ul>
                        {% if data_date %}
                            {% for date in data_date %}
                                <li><a href='{% url 'blog:date' date|date:'Y' date|date:'m' %}'>{{ date|date:'Y-m' }}</a></li>
                            {% endfor %}
                        {% else %}
                            <div>近期没有发表过文章</div>
                        {% endif %}
                    </ul>
                </div>
                <!--文章归档结束-->

                <!--猜你喜欢-->
                <div class="widget d_postlist">
                    <div class="title"><h2>猜你喜欢</h2></div>
                    <ul>
                        {% get_article_list 'loves' 6 as hot_tag %}
                        {% for hot in hot_tag %}
                        <li>
                            <a href="/article/{{ hot.slug }} " title="{{ hot.title }}"><span class="thumbnail"><img
                                src="{{ hot.img_link }}" alt="{{ hot.title }}"/></span>
                                <span class="text">{{ hot.title }}</span>
                                <span class="muted">{{ hot.create_date|date:'Y-m-d' }}</span>
                                <span class="muted">{{ hot.loves }}喜欢</span>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <!--猜你喜欢结束-->

            <!--标签云-->
            <div class="widget d_tag">
                <div class="title"><h2>标签云</h2></div>
                <div class="d_tags">
                    {% get_tag_list as tags %}
                    {% for tag in tags %}
                        <a title="{{ tag.total_num }}个话题" href="{% url 'blog:tag' tag.name %}">{{ tag.name }} ({{ tag.total_num }})</a>
                    {% endfor %}
                </div>
            </div>
            <!--标签云结束-->

            <!--友情链接-->
            <div class="widget widget_links">
                <div class="title"><h2>友情链接</h2></div>
                    {% get_friends as friends %}
                    <ul class='xoxo blogroll'>
                        {% if friends %}
                            {% for friend in friends %}
                                <li><a href="{{ friend.link }}" target="_blank">{{ friend.name }}</a></li>
                            {% endfor %}
                        {% else %}
                            <div>&nbsp;&nbsp;暂无友链，欢迎来战</div>
                        {% endif %}
                    </ul>
            </div>
            <!--友情链接结束-->

            <!--精品推荐-->
            <div class="widget widget_text">
                <div class="title"><h2>精品推荐</h2></div>
                <div class="text widget">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;广告位诚邀加盟
                </div>
            </div>

            <!--精品推荐结束-->
            <div class="widget widget_text">

            </div>
        </aside>
{% endblock right %}

templates/comment_list.html
{% load staticfiles %}
{% load comment_tags oauth_tags %}
<div id="respond" class="no_webshot">
		<form action="/comment/add" method="post" id="commentform">

		<div class="comt-title">
            {% if request.session.username|default:'' != '' %}
            {% get_user_data request.session.uid as user %}
                <div class="comt-avatar pull-left">
                    <img alt='' src='/media/{{ user.avatar }}' class='avatar avatar-54 photo avatar-default' height='54' width='54' />			    </div>
                <div class="comt-author pull-left" id="nick">
                {{ request.session.username }}
                </div>
            {% endif %}

            {% if request.session.nick|default:'' != '' %}
                {% get_tourist_data request.session.tid as tourist %}
                <div class="comt-avatar pull-left">
                    <img alt='' src='/media/avatar' class='avatar avatar-54 photo avatar-default' height='54' width='54' />			    </div>
                <div class="comt-author pull-left" id="nick">
                {{ tourist.nickname }}

                &nbsp; <a class="switch-author" href="javascript:;" data-type="switch-author" style="font-size:12px;">换个身份</a>

                </div>
                {% else %}

                <div class="comt-author pull-left" id="nick">

                </div>
            {% endif %}

			<a id="cancel-comment-reply-link" class="pull-right" href="javascript:;">取消评论</a>
		</div>

		<div class="comt">
			<div class="comt-box">
                <h3>发表我的评论</h3>
				<textarea placeholder="写点什么..." class="input-block-level comt-area" name="w" id="comment" cols="100%" rows="3" tabindex="1" onkeydown="if(event.ctrlKey&amp;&amp;event.keyCode==13){document.getElementById('submit').click();return false};"></textarea><textarea name="comment" cols="100%" rows="4" style="display:none"></textarea>
				<div class="comt-ctrl">
					<button class="btn btn-primary pull-right" type="submit" name="submit" id="submit" tabindex="5"><i class="fa fa-check-square-o"></i> 提交评论</button>
					<div class="comt-tips pull-right"><input type='hidden' name='comment_post_ID' value='{{ category }}' id='comment_post_ID' />
<input type='hidden' name='comment_parent' id='comment_parent' value='0' />
<p style="display: none;"><input type="hidden" id="akismet_comment_nonce" name="akismet_comment_nonce" value="da9dc5c77a" /></p><p style="display: none;"><input type="hidden" id="ak_js" name="ak_js" value="50"/></p></div>
					<span data-type="comment-insert-smilie" class="muted comt-smilie"><i class="fa fa-smile-o"></i> 表情</span>
					<span class="muted comt-mailme"><label for="comment_mail_notify" class="checkbox inline" style="padding-top:0"><input type="checkbox" name="comment_mail_notify" id="comment_mail_notify" value="comment_mail_notify" checked="checked"/>有人回复时邮件通知我</label></span>
				</div>
			</div>

												<div class="comt-comterinfo" id="comment-author-info" >
						<h4>Hi，您需要填写昵称和邮箱！</h4>
						<ul>
							<li class="form-inline"><label class="hide" for="author">昵称</label><input class="ipt" type="text" name="author" id="author" value="{% if user %}{{ user.username }}{% elif tourist %}{{ tourist.nickname }}{% endif %}" tabindex="2" placeholder="昵称"><span class="help-inline">昵称 (必填)</span></li>
							<li class="form-inline"><label class="hide" for="email">邮箱</label><input class="ipt" type="text" name="email" id="email" value="{% if user %}{{ user.email }}{% elif tourist %}{{ tourist.email }}{% endif %}" tabindex="3" placeholder="邮箱"><span class="help-inline">邮箱 (必填)</span></li>
							<li class="form-inline"><label class="hide" for="url">网址</label><input class="ipt" type="text" name="url" id="url" value="{% if user %}{{ user.link }}{% elif tourist %}{{ tourist.address }}{% endif %}" tabindex="4" placeholder="网址"><span class="help-inline">网址</span></li>
						</ul>
					</div>
									</div>


	</form>
	</div>

<div id="postcomments">

{% if category == 'message'%}

    {% get_comment_user_count category as  user_num%}
    {% build_comment_tree category request.path as htm %}
{% elif category == 'about' %}
    {% get_comment_user_count category as  user_num%}
    {% build_comment_tree category request.path as htm %}
{% else %}
    {% get_comment_user_count category category as  user_num%}
    {% build_comment_tree category  request.path category as htm %}
{% endif %}
<div id="comments">
		<i class="fa fa-comments-o"></i> <b> ({{ user_num }})</b>个小伙伴在吐槽
	</div>
   {{ htm }}
<div class="commentnav"	>
			</div>
</div>

templates/content.html
{%extends 'base_right.html'%}
{% load comment_tags blog_tags %}

{% block description %}
    <meta name="description" content="{% get_title category as c %}{{ c.description }}"/>
    {% endblock description %}
    {% block keywords %}
    <meta name="keywords" content="{% get_title category as c %}{{ c.keywords }}"/>
    {% endblock keywords %}
{% block title %}{% get_title category as c %}静觅丨{{ c.name }}{% endblock title %}

{%block body%}
	<div class="content-wrap">
	    <div class="content">
		    <header class="archive-header">
			    <h1><i class="fa fa-folder-open"></i>  &nbsp;分类：福利专区  <a title="订阅福利专区" target="_blank" href="{% url 'blog:category' resources '' %}"><i class="rss fa fa-rss"></i></a></h1>
					</header>
        {% for article in page_obj %}
				<article class="excerpt">
	<header><a class="label label-important" href="/category/{{ article.category.bigcategory.name }}/{{ article.category.name|lower }}">{{ article.category.name }}<i class="label-arrow"></i></a><h2><a target="_blank" href="/article/{{ article.slug }}" title="{{ article.title }}">{{ article.title }} </a></h2>
	</header>
	<div class="focus"><a target="_blank" href="/article/{{ article.slug }}"><img class="thumb" width="200" height="123" src="{{ article.img_link }}" alt="{{ article.title }}" /></a></div>
			<span class="note"> {{ article.summary }}</span>
<p class="auth-span">
		<span class="muted"><i class="fa fa-user"></i> <a href="/author/{{ article.author }}">{{ article.author }}</a></span>
		<span class="muted"><i class="fa fa-clock-o"></i> {{ article.create_date|date:'Y-m-d'}}</span>	<span class="muted"><i class="fa fa-eye"></i> {{ article.views }}浏览</span>	<span class="muted"><i class="fa fa-comments-o"></i> <a target="_blank" href="/article/{{ article.slug }}#comments">{% get_comment_count article.id  article.id%}评论</a></span><span class="muted">
<a href="javascript:;" data-action="ding" data-id="455" id="Addlike" class="action"><i class="fa fa-heart-o"></i><span class="count">{{ article.love }}</span>喜欢</a></span></p>
</article>
        {% empty %}
                <div class="no-post">当前分类下还没有发布的文章！</div>
        {% endfor %}
{% if is_paginated %}
            <div class="pagination">
                <ul>
                    {% if first %}
                        <li><a href="?page=1">1</a></li>
                    {% endif %}
                    {% if left %}
                        {% if left_has_more %}
                            <li><span>...</span></li>
                        {% endif %}
                        {% for i in left %}
                            <li class="prev-page"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                    {% endif %}
                    <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                    {% if right %}
                        {% for i in right %}
                            <li class="next-page"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                        {% if right_has_more %}
                            <li><span>...</span></li>
                        {% endif %}
                    {% endif %}
                    {% if last %}
                        <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
        </div>
    </div>
{%endblock body%}

templates/index.html
{%extends 'base_right.html'%}
{% load blog_tags static comment_tags%}

{% block title %}静觅 | StormSha的个人博客{% endblock title %}
{% block description %}
<meta name="description" content="StormSha的个人博客，记录生活的瞬间，分享学习的心得，感悟生活，留住感动，静静寻觅生活的美好"/>
{% endblock description %}
{% block keywords %}
<meta name="keywords" content="StormSha,Python,Django,静觅,网络,IT,技术,博客,个人博客"/>
{% endblock keywords %}
{% block body%}
    <div class="content-wrap">
        <div class="content">
            <div id="wowslider-container1">
                <div class="ws_images">

                    <ul>
                        {% get_carousel_index as carousels %}
                        {% for carousel in carousels %}

                        <li>
                            <a target="_blank" href="{{ carousel.url }}" title="{{ carousel.content }}">
                                <img src="{{ carousel.img_url }}" title="{{ carousel.title }}" alt="{{ carousel.title }}"/>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="ws_thumbs">
                    <div>
                        {% get_carousel_index as carousels%}
                        {% for carousel in carousels %}
                        <a target="_blank" href="#" title="{{ carousel.title }}"><img src="{{ carousel.img_url }}"/></a>
                        {% endfor %}
                    </div>
                </div>
                <div class="ws_shadow"></div>
            </div>
            <script type="text/javascript" src="/static/js/slider.js"></script>
            <div>
                <div class="left-ad" style="clear: both;background-color: #fff; width: 30%;float: left;margin-right:2%;"></div>
                <div class="hot-posts">
                    <h2 class="title">热门排行</h2>
                    <ul>
                        {% get_article_list 'views' 5 as hot_article %}
                            {% for hot in hot_article %}
                            <li>
                                <p><span class="muted">
                                    <a href="javascript:;" data-action="ding" data-id="{{ hot.id }}" id="Addlike" class="action">
                                        <i class="fa fa-heart-o"></i><span class="count">{{ hot.loves }}</span> 喜欢</a>
                                    </span>
                                </p>
                                <span class="label label-1">{{ forloop.counter}}</span>
                                <a href="/article/{{ hot.slug }}" title="{{ hot.title }}">{{ hot.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% for article in page_obj %}
            <article class="excerpt">
                <header><a class="label label-important" href="/category/{{ article.category.bigcategory.name }}/{{ article.category.name|lower }}">{{ article.category.name }}<i class="label-arrow"></i></a>
                    <h2><a target="_blank" href="/article/{{ article.slug }}" title="{{ article.title }}">{{ article.title }} </a></h2>
                </header>
                <div class="focus">
                    <a target="_blank" href="{{ article.get_absolute_url }}">
                        <img class="thumb" width="200" height="123" src="{{ article.img_link }}" alt="{{ article.title }}"/>
                    </a>
                </div>
                <span class="note">{{ article.summary }}</span>
                <p class="auth-span">
                    <span class="muted"><i class="fa fa-user"></i>
                        <a href="{% url 'accounts:profile' %}?next={{ request.path }}">{{ article.author }}</a>
                    </span>
                    <span class="muted"><i class="fa fa-clock-o"></i> {{ article.create_date|date:'Y-m-d' }}</span>
                    <span class="muted"><i class="fa fa-eye"></i> {{ article.views }}浏览</span>
                    <span class="muted"><i class="fa fa-comments-o"></i>
                        <a target="_blank" href="/article/{{ article.slug }}#comments">{% get_comment_count article.id  article.id%}评论</a>
                    </span>
                    <span class="muted"><a href="javascript:;" data-action="ding" data-id="{{ article.id }}" id="Addlike" class="action">
                        <i class="fa fa-heart-o"></i><span class="count">{{ article.loves }}</span>喜欢</a>
                    </span>
                </p>
            </article>
        {% empty %}
            <div class="no-post">暂时还没有发布的文章！</div>
        {% endfor %}

        {% if is_paginated %}
            <div class="pagination">
                <ul>
                    {% if first %}
                        <li><a href="?page=1">1</a></li>
                    {% endif %}
                    {% if left %}
                        {% if left_has_more %}
                            <li><span>...</span></li>
                        {% endif %}
                        {% for i in left %}
                            <li class="prev-page"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                    {% endif %}
                    <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                    {% if right %}
                        {% for i in right %}
                            <li class="next-page"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                        {% if right_has_more %}
                            <li><span>...</span></li>
                        {% endif %}
                    {% endif %}
                    {% if last %}
                        <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}

        </div>
    </div>

{%endblock body%}

templates/message.html
{%extends 'base.html' %}
{% load blog_tags %}
{% block title %}静觅丨给我留言{% endblock title %}

{% block description %}
    <meta name="description" content="{% get_title category as bigcategory %}{{ bigcategory.description }}"/>
    {% endblock description %}
    {% block keywords %}
    <meta name="keywords" content="{% get_title category as bigcategory %}{{ bigcategory.keywords }}"/>
    {% endblock keywords %}
{%block body%}
<div class="pagewrapper clearfix">
	
	
		<header class="pageheader clearfix">
			<h1 class="pull-left">
				<a href="https://cuiqingcai.com/message">给我留言</a>
			</h1>
			<div class="pull-right"><!-- 百度分享 -->
	<span class="action action-share bdsharebuttonbox"><i class="fa fa-share-alt"></i>分享 (<span class="bds_count" data-cmd="count" title="累计分享0次">0</span>)<div class="action-popover"><div class="popover top in"><div class="arrow"></div><div class="popover-content"><a href="#" class="sinaweibo fa fa-weibo" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_qzone fa fa-star" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="tencentweibo fa fa-tencent-weibo" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="qq fa fa-qq" data-cmd="sqq" title="分享到QQ好友"></a><a href="#" class="bds_renren fa fa-renren" data-cmd="renren" title="分享到人人网"></a><a href="#" class="bds_weixin fa fa-weixin" data-cmd="weixin" title="分享到微信"></a><a href="#" class="bds_more fa fa-ellipsis-h" data-cmd="more"></a></div></div></div></span>			</div>
		</header>


{% include 'comment_list.html' %}
	
</div>
{%endblock body%}